export const cursos = [
  {
    id: "7cf00315-225c-4217-82e7-7badd5683ehe",
    nome: "Alfabeto e sons",
    titulo: "Alfabeto e sons",
    concluido: 0,
    atividades: [
      { nome: "Conteúdo", concluida: false },
      {
        nome: "Quizz",
        concluida: false,
        perguntas: [
          {
            id: 1,
            sentence: "Pronounce these letters: A W B Z",
            tutoringText: "êi - dâbeliu - bí - zí",
            type: "pronunciation",
          },
          {
            id: 2,
            sentence: "Pronounce these vowels: E I O U",
            tutoringText: "í - ái - ôu - iú",
            type: "pronunciation",
          },
          {
            id: 3,
            sentence: "Pronounce these letters: G J H K",
            tutoringText: "djí - djêi - êitch - quêi",
            type: "pronunciation",
          },
          {
            id: 4,
            sentence: "Pronounce these letters: R S X Y",
            tutoringText: "ár - és - écs - uái",
            type: "pronunciation",
          },
          {
            id: 5,
            sentence: "Pronounce these letters: F L M N",
            tutoringText: "éf - él - ém - én",
            type: "pronunciation",
          },
          {
            id: 6,
            sentence: "Pronounce these letters: P Q T V",
            tutoringText: "pí - quiú - tí - ví",
            type: "pronunciation",
          },
          {
            id: 7,
            sentence: "Spell the word: 'GAME'",
            tutoringText: "djêi - êi - ém - í",
            type: "pronunciation",
          },
          {
            id: 8,
            sentence: "Spell the word: 'CITY'",
            tutoringText: "cí - ái - tí - uái",
            type: "pronunciation",
          },
        ],
      },
      { nome: "Pós-teste", concluida: false },
    ],
    completo: false,
  },
  {
    id: "7cf00315-225c-4217-82e7-7badd5681eee",
    nome: "to-be",
    titulo: "Aprenda a se apresentar, a perguntar de outra pessoa e a entender a função do verbo To Be",
    descricao: "",
    concluido: 0,
    atividades: [
      {
        nome: "Pré-teste",
        perguntas: [
          {
            titulo: "Escolha a resposta correta:",
            descricao: "I .......................... a teacher.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 1,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "You ...................... a great student.",
            opcoes: ["am", "is", "are", "do"],
            opcaoCorreta: 2,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "He ........................... a chef.",
            opcoes: ["am", "are", "do", "is"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "She ........................... a police officer.",
            opcoes: ["am", "are", "do", "is"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "It ...................... a good tool for my job.",
            opcoes: ["am", "are", "do", "is"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "We ............... engineers.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 2,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "They ..................... doctors.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 2,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "My sister and I ...................... lawyers.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 2,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "My cousin .......................... a firefighter.",
            opcoes: ["am", "are", "do", "is"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "The boss and the secretary .................................... in the meeting.",
            opcoes: ["am", "do", "is", "are"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "The client ........................ waiting outside.",
            opcoes: ["am", "are", "do", "is"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "I .......................... working as a journalist.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 1,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "She ........................... the new manager.",
            opcoes: ["am", "are", "do", "is"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "You and he ......................... marketing specialists.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 2,
          },
        ],
        concluida: false,
        dataConclusao: "",
      },
      {
        nome: "Conteúdo",
        conteudoASerImportado: "conteudos/verbotobe.html",
        videos: [
          {
            videoId: "verbotobe.mp4",
          },
        ],
        concluida: true,
      },
      {
        nome: "Quizz",
        concluida: false,
        perguntas: [
          {
            id: 1,
            sentence: "I ___ a student.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "am",
            tutoringText: "O pronome 'I' usa sempre a forma 'am' no presente do verbo 'to be'.",
          },
          {
            id: 2,
            sentence: "Barbara ___ not at home.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "is",
            tutoringText: "'Barbara' (singular, She) usa 'is not' ou 'isn't'.",
          },
          {
            id: 3,
            sentence: "___ you happy?",
            options: ["Is", "Are", "Am", "Be"],
            correctAnswer: "Are",
            tutoringText: "Na forma interrogativa, 'you' usa 'Are'.",
          },
          {
            id: 4,
            sentence: "Josh and Ricky ___ teachers.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "are",
            tutoringText: "'Josh and Ricky' (plural, They) usa 'are' no presente afirmativo.",
          },
          {
            id: 5,
            sentence: "We ___ not witches.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "are",
            tutoringText: "Na negativa, 'we' usa 'are not' ou 'aren't'.",
          },
          {
            id: 6,
            sentence: "___ Alan an accountant?",
            options: ["Is", "Are", "Am", "Be"],
            correctAnswer: "Is",
            tutoringText: "'Alan' (singular, He) usa 'Is' na forma interrogativa.",
          },
          {
            id: 7,
            sentence: "I ___ not a vampire.",
            options: ["is", "am", "are", "be"],
            correctAnswer: "am",
            tutoringText: "'I' na negativa usa 'am not'.",
          },
          {
            id: 8,
            sentence: "You ___ a witch.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "are",
            tutoringText: "'You' no presente afirmativo usa 'are'.",
          },
          {
            id: 9,
            sentence: "___ they vampires?",
            options: ["Is", "Are", "Am", "Be"],
            correctAnswer: "Are",
            tutoringText: "Na forma interrogativa, 'they' usa 'Are'.",
          },
          {
            id: 10,
            sentence: "Kevin ___ not a doctor.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "is",
            tutoringText: "'Kevin' (singular, He) usa 'is not' ou 'isn't' na negativa.",
          },
          {
            id: 11,
            sentence: "My friends ___ brothers and sisters.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "are",
            tutoringText: "'My parents' (plural, They) usa 'are' no presente afirmativo.",
          },
          {
            id: 12,
            sentence: "___ I human?",
            options: ["Is", "Are", "Am", "Be"],
            correctAnswer: "Am",
            tutoringText: "Na forma interrogativa, 'I' usa 'Am'.",
          },
          {
            id: 13,
            sentence: "Laura ___ a nurse.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "is",
            tutoringText: "'Laura' (singular, She) no afirmativo usa 'is'.",
          },
          {
            id: 14,
            sentence: "You ___ not my friend.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "are",
            tutoringText: "'You' na forma negativa usa 'are not' ou 'aren't'.",
          },
          {
            id: 15,
            sentence: "___ Paul a doctor or an engineer?",
            options: ["Is", "Are", "Am", "Be"],
            correctAnswer: "Is",
            tutoringText: "'Paul' (singular, He) usa 'Is' na forma interrogativa.",
          },
          {
            id: 16,
            sentence: "The paiting ___ a beautiful landscape.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "is",
            tutoringText: "'The meeting' (singular, It) usa a forma 'is' no presente.",
          },
          {
            id: 17,
            sentence: "We ___ in the office right now.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "are",
            tutoringText: "'We' usa 'are' para indicar a localização no presente.",
          },
          {
            id: 18,
            sentence: "Our colleagues ___ not ready for the exam.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "are",
            tutoringText: "'Our colleagues' (plural, They) usa 'are not' ou 'aren't' na negativa.",
          },
          {
            id: 19,
            sentence: "___ Martha a lawyer?",
            options: ["Is", "Are", "Am", "Be"],
            correctAnswer: "Is",
            tutoringText: "'Martha' (singular, She) usa 'Is' na forma interrogativa.",
          },
          {
            id: 20,
            sentence: "I ___ hungry.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "am",
            tutoringText: "",
          },
        ],
        dataConclusao: "",
      },
      {
        nome: "Texto",
        concluida: false,
        texto: "",
        perguntas: [
          {
            descricao: "Ana é programadora de computador",
            correta: false,
          },
        ],
      },
      {
        nome: "Agendamento",
        concluida: false,
        descricao: "Agende um horário de aula para tirar dúvidas com relação ao Verbo To Be",
      },
      {
        nome: "Pós-teste",
        concluida: false,
        perguntas: [
          {
            titulo: "Escolha a resposta correta:",
            descricao: "I .......................... a teacher.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 1,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "You ...................... a great student.",
            opcoes: ["am", "is", "are", "do"],
            opcaoCorreta: 2,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "He ........................... a chef.",
            opcoes: ["am", "are", "do", "is"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "She ........................... a police officer.",
            opcoes: ["am", "are", "do", "is"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "It ...................... a good tool for my job.",
            opcoes: ["am", "are", "do", "is"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "We ............... engineers.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 2,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "They ..................... doctors.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 2,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "My sister and I ...................... lawyers.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 2,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "My cousin .......................... a firefighter.",
            opcoes: ["am", "are", "do", "is"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "The boss and the secretary .................................... in the meeting.",
            opcoes: ["am", "do", "is", "are"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "The client ........................ waiting outside.",
            opcoes: ["am", "are", "do", "is"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "I .......................... working as a journalist.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 1,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "She ........................... the new manager.",
            opcoes: ["am", "are", "do", "is"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "You and he ......................... marketing specialists.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 2,
          },
        ],
        dataConclusao: "",
      },
    ],
    completo: false,
  },
  {
    id: "7cf00315-225c-4217-82e7-7badd5683ehe",
    nome: "Fazendo pedidos em café/restaurante",
    titulo: "Artigos A/AN/THE e Personal Pronouns",
    concluido: 0,
    atividades: [
      { nome: "Conteúdo", concluida: false },
      {
        nome: "Quizz",
        concluida: false,
        perguntas: [
          {
            id: 9,
            sentence: "Complete: '___ apple is on the table.'",
            options: ["A", "An", "On", "In"],
            correctAnswer: "An",
            tutoringText: "Usamos 'an' antes de palavras que começam com som de vogal.",
          },
          {
            id: 10,
            sentence: "Replace the subject: 'Maria is happy.'",
            options: ["He", "She", "It", "They"],
            correctAnswer: "She",
            tutoringText: "Maria é um sujeito feminino singular, logo usamos 'She'.",
          },
          {
            id: 11,
            sentence: "Complete: 'I have a car. ___ car is blue.'",
            options: ["A", "An", "The", "It"],
            correctAnswer: "The",
            tutoringText: "Usamos 'the' para falar de algo que já foi mencionado anteriormente.",
          },
          {
            id: 12,
            sentence: "Replace the subject: 'The dog is hungry.'",
            options: ["He", "She", "It", "We"],
            correctAnswer: "It",
            tutoringText: "Para animais ou objetos no singular, o pronome neutro é 'It'.",
          },
          {
            id: 13,
            sentence: "Complete: 'It is ___ honor to meet you.'",
            options: ["a", "an", "the", "no article"],
            correctAnswer: "an",
            tutoringText: "A palavra 'honor' tem o 'H' mudo, começando com som de vogal.",
          },
          {
            id: 14,
            sentence: "Replace the subject: 'John and I are friends.'",
            options: ["They", "You", "We", "He"],
            correctAnswer: "We",
            tutoringText: "Quando você está incluído no grupo ('John and I'), o pronome é 'We'.",
          },
          {
            id: 15,
            sentence: "Complete: 'She is ___ university student.'",
            options: ["a", "an", "the", "any"],
            correctAnswer: "a",
            tutoringText: "'University' começa com som de consoante 'yu', por isso usamos 'a'.",
          },
          {
            id: 16,
            sentence: "Replace the subject: 'The books are old.'",
            options: ["It", "They", "We", "You"],
            correctAnswer: "They",
            tutoringText: "Para objetos no plural, usamos 'They'.",
          },
          {
            id: 17,
            sentence: "Complete: 'Can you see ___ moon?'",
            options: ["a", "an", "the", "this"],
            correctAnswer: "the",
            tutoringText: "Usamos 'the' para objetos únicos no mundo, como a lua.",
          },
          {
            id: 18,
            sentence: "Complete: '___ am a teacher.'",
            options: ["He", "She", "I", "You"],
            correctAnswer: "I",
            tutoringText: "O verbo 'am' é usado exclusivamente com o pronome 'I'.",
          },
        ],
      },
      { nome: "Pós-teste", concluida: false },
    ],
    completo: false,
  },
  {
    id: "7cf00315-225c-4217-82e7-7badd5683ehe",
    nome: "Dar seu telefone e entender preços",
    titulo: "Numbers from 0 to 100",
    concluido: 0,
    atividades: [
      { nome: "Conteúdo", concluida: false },
      {
        nome: "Quizz",
        concluida: false,
        perguntas: [
          {
            id: 19,
            sentence: "How do you write the number 13?",
            options: ["Thirty", "Thirteen", "Three", "Third"],
            correctAnswer: "Thirteen",
            tutoringText: "Números de 13 a 19 terminam em '-teen'. Não confunda com 'Thirty' (30).",
          },
          {
            id: 20,
            sentence: "What is the result of: Ten + Twenty?",
            options: ["Twelve", "Twenty-one", "Thirty", "Forty"],
            correctAnswer: "Thirty",
            tutoringText: "10 (Ten) + 20 (Twenty) = 30 (Thirty).",
          },
          {
            id: 21,
            sentence: "How do you write the number 40?",
            options: ["Fourty", "Forty", "Fourteen", "Four"],
            correctAnswer: "Forty",
            tutoringText: "Atenção: 'Four' tem a letra 'U', mas 'Forty' (40) não tem.",
          },
          {
            id: 22,
            sentence: "Complete the sequence: 20, 21, 22, ___",
            options: ["Twenty-three", "Twenty-four", "Twelve", "Twenty-two"],
            correctAnswer: "Twenty-three",
            tutoringText: "A sequência segue o número 23 (Twenty-three).",
          },
          {
            id: 23,
            sentence: "How do you write the number 55?",
            options: ["Fifty-five", "Five-five", "Fifteen-five", "Fifty-fift"],
            correctAnswer: "Fifty-five",
            tutoringText: "Para dezenas compostas, usamos a dezena (Fifty) + o número (five).",
          },
          {
            id: 24,
            sentence: "What is the number 0 called in English?",
            options: ["One", "Null", "Zero", "None"],
            correctAnswer: "Zero",
            tutoringText: "O número 0 é 'Zero' (em contextos informais ou esportivos também pode ser 'Oh' ou 'Nil').",
          },
          {
            id: 25,
            sentence: "Which number is 'Seventy'?",
            options: ["17", "7", "70", "700"],
            correctAnswer: "70",
            tutoringText: "Terminações em '-ty' indicam dezenas exatas (70).",
          },
          {
            id: 26,
            sentence: "How do you spell 12?",
            options: ["Twelve", "Twelvee", "Tuelv", "Twenty"],
            correctAnswer: "Twelve",
            tutoringText: "12 é 'Twelve'. Não confunda com 20 (Twenty).",
          },
          {
            id: 27,
            sentence: "What is the result of: Fifty + Fifty?",
            options: ["Ninety", "One hundred", "Eighty", "Sixty"],
            correctAnswer: "One hundred",
            tutoringText: "50 + 50 = 100, que se diz 'One hundred' ou 'A hundred'.",
          },
          {
            id: 28,
            sentence: "How do you write 88?",
            options: ["Eighty-eight", "Eight-eight", "Eighteen-eight", "Eighty-eighty"],
            correctAnswer: "Eighty-eight",
            tutoringText: "Eighty (80) + eight (8) = Eighty-eight.",
          },
        ],
      },
      { nome: "Pós-teste", concluida: false },
    ],
    completo: false,
  },
  {
    id: "7cf00315-225c-4217-82e7-7badd5683ehe",
    nome: "Comprar itens no supermercado",
    titulo: "Substantivos contáveis",
    concluido: 0,
    atividades: [
      { nome: "Conteúdo", concluida: false },
      {
        nome: "Quizz",
        concluida: false,
        perguntas: [
          {
            id: 29,
            sentence: "Which is the plural of 'Child'?",
            options: ["Childs", "Children", "Childrens", "Childes"],
            correctAnswer: "Children",
            tutoringText: "'Child' tem um plural irregular. Nunca usamos 's' em 'Children'.",
          },
          {
            id: 30,
            sentence: "How many ___ are in the classroom?",
            options: ["student", "students", "studying", "studentes"],
            correctAnswer: "students",
            tutoringText: "A expressão 'How many' é usada apenas com substantivos contáveis no plural.",
          },
          {
            id: 31,
            sentence: "I have two ___ in my kitchen.",
            options: ["knife", "knifes", "knives", "knivs"],
            correctAnswer: "knives",
            tutoringText: "Substantivos terminados em 'fe' geralmente mudam para 'ves' no plural.",
          },
          {
            id: 32,
            sentence: "I saw three ___ in the park.",
            options: ["mouse", "mouses", "mices", "mice"],
            correctAnswer: "mice",
            tutoringText: "O plural de 'mouse' (camundongo) é irregular: 'mice'.",
          },
          {
            id: 33,
            sentence: "She has ___ orange in her bag.",
            options: ["a", "an", "many", "some"],
            correctAnswer: "an",
            tutoringText: "Usamos 'an' para um único item contável que começa com som de vogal.",
          },
          {
            id: 34,
            sentence: "Which is the correct plural for 'City'?",
            options: ["Citys", "Cities", "Cityes", "Citis"],
            correctAnswer: "Cities",
            tutoringText: "Palavras terminadas em 'consoante + Y', trocamos o 'Y' por 'ies'.",
          },
          {
            id: 35,
            sentence: "There are many ___ on the farm.",
            options: ["sheep", "sheeps", "sheepes", "ship"],
            correctAnswer: "sheep",
            tutoringText: "'Sheep' (ovelha) é um substantivo que tem a mesma forma no singular e no plural.",
          },
          {
            id: 36,
            sentence: "I can see five ___ waiting for the bus.",
            options: ["person", "persons", "people", "peoples"],
            correctAnswer: "people",
            tutoringText: "Embora 'persons' exista, 'people' é o plural comum e contável de 'person'.",
          },
          {
            id: 37,
            sentence: "He wants to buy ___ new car.",
            options: ["a", "an", "many", "few"],
            correctAnswer: "a",
            tutoringText: "Usamos 'a' para substantivos contáveis no singular que começam com som de consoante.",
          },
          {
            id: 38,
            sentence: "Are there ___ chairs in the room?",
            options: ["much", "any", "a", "an"],
            correctAnswer: "any",
            tutoringText: "Usamos 'any' para perguntas com substantivos contáveis no plural.",
          },
        ],
      },
      { nome: "Pós-teste", concluida: false },
    ],
    completo: false,
  },
  {
    id: "7cf00315-225c-4217-82e7-7badd5683ehe",
    nome: "Descrever seu quarto/casa",
    titulo: "There is / There are",
    concluido: 0,
    atividades: [
      { nome: "Conteúdo", concluida: false },
      {
        nome: "Quizz",
        concluida: false,
        perguntas: [
          {
            id: 39,
            sentence: "Complete: '___ a book on the desk.'",
            options: ["There is", "There are", "Is there", "Are there"],
            correctAnswer: "There is",
            tutoringText: "Usamos 'There is' para um único objeto (singular).",
          },
          {
            id: 40,
            sentence: "Complete: '___ many students in the classroom.'",
            options: ["There is", "There are", "Is there", "Are there"],
            correctAnswer: "There are",
            tutoringText: "Usamos 'There are' para vários objetos ou pessoas (plural).",
          },
          {
            id: 41,
            sentence: "Question: '___ any milk in the fridge?'",
            options: ["There is", "There are", "Is there", "Are there"],
            correctAnswer: "Is there",
            tutoringText: "Em perguntas no singular ou com incontáveis (milk), invertemos para 'Is there'.",
          },
          {
            id: 42,
            sentence: "Negative: '___ any chairs in this room.'",
            options: ["There isn't", "There aren't", "There not", "Isn't there"],
            correctAnswer: "There aren't",
            tutoringText: "Para frases negativas no plural, usamos 'There aren't'.",
          },
          {
            id: 43,
            sentence: "Complete: '___ a cat under the car.'",
            options: ["There is", "There are", "Is there", "Are there"],
            correctAnswer: "There is",
            tutoringText: "Identificamos 'a cat' (um gato) como singular, logo 'There is'.",
          },
          {
            id: 44,
            sentence: "Question: '___ seven days in a week?'",
            options: ["Is there", "Are there", "There is", "There are"],
            correctAnswer: "Are there",
            tutoringText: "Para perguntas no plural, usamos a estrutura 'Are there'.",
          },
          {
            id: 45,
            sentence: "Negative: '___ a mistake in your homework.'",
            options: ["There aren't", "There isn't", "There not", "Is there"],
            correctAnswer: "There isn't",
            tutoringText: "Para frases negativas no singular, usamos 'There isn't'.",
          },
          {
            id: 46,
            sentence: "Complete: '___ three apples in the bowl.'",
            options: ["There is", "There are", "There isn't", "Is there"],
            correctAnswer: "There are",
            tutoringText: "Como temos 'three apples' (três maçãs), o correto é 'There are'.",
          },
          {
            id: 47,
            sentence: "Question: '___ a supermarket near here?'",
            options: ["Are there", "There is", "Is there", "There are"],
            correctAnswer: "Is there",
            tutoringText: "Estrutura interrogativa para singular: 'Is there + objeto?'.",
          },
          {
            id: 48,
            sentence: "Complete: '___ some people waiting for you.'",
            options: ["There is", "There are", "Is there", "There isn't"],
            correctAnswer: "There are",
            tutoringText: "'People' é o plural de 'person', por isso usamos 'There are'.",
          },
        ],
      },
      { nome: "Pós-teste", concluida: false },
    ],
    completo: false,
  },
  {
    id: "7cf00315-225c-4217-82e7-7badd5683ehe",
    nome: "Dar e entender direções simples",
    titulo: "Preposições básicas",
    concluido: 0,
    atividades: [
      { nome: "Conteúdo", concluida: false },
      {
        nome: "Quizz",
        concluida: false,
        perguntas: [
          {
            id: 49,
            sentence: "Complete: 'My birthday is ___ July.'",
            options: ["in", "on", "at", "to"],
            correctAnswer: "in",
            tutoringText: "Usamos 'in' para meses, anos e estações do ano (períodos longos).",
          },
          {
            id: 50,
            sentence: "Complete: 'The book is ___ the table.'",
            options: ["in", "on", "at", "under"],
            correctAnswer: "on",
            tutoringText: "Usamos 'on' para superfícies de contato.",
          },
          {
            id: 51,
            sentence: "Complete: 'I have a meeting ___ 9 o'clock.'",
            options: ["in", "on", "at", "by"],
            correctAnswer: "at",
            tutoringText: "Usamos 'at' para horários específicos e momentos exatos.",
          },
          {
            id: 52,
            sentence: "Complete: 'We go to the beach ___ summer.'",
            options: ["at", "on", "in", "to"],
            correctAnswer: "in",
            tutoringText: "Usamos 'in' para estações do ano (summer, winter, etc).",
          },
          {
            id: 53,
            sentence: "Complete: 'She lives ___ 125 Main Street.'",
            options: ["in", "on", "at", "from"],
            correctAnswer: "at",
            tutoringText: "Usamos 'at' para endereços completos com número.",
          },
          {
            id: 54,
            sentence: "Complete: 'The party is ___ Friday night.'",
            options: ["in", "on", "at", "during"],
            correctAnswer: "on",
            tutoringText: "Usamos 'on' para dias da semana e datas específicas.",
          },
          {
            id: 55,
            sentence: "Complete: 'There is a key ___ my pocket.'",
            options: ["on", "at", "in", "over"],
            correctAnswer: "in",
            tutoringText: "Usamos 'in' para indicar que algo está dentro de um espaço fechado.",
          },
          {
            id: 56,
            sentence: "Complete: 'I study ___ the morning.'",
            options: ["at", "on", "in", "by"],
            correctAnswer: "in",
            tutoringText: "Usamos 'in' para partes do dia (in the morning/afternoon/evening), mas 'at night'.",
          },
          {
            id: 57,
            sentence: "Complete: 'My house is ___ Oxford Street.'",
            options: ["at", "on", "in", "to"],
            correctAnswer: "on",
            tutoringText: "Usamos 'on' para nomes de ruas ou avenidas (sem o número).",
          },
          {
            id: 58,
            sentence: "Complete: 'They are ___ the airport right now.'",
            options: ["in", "on", "at", "into"],
            correctAnswer: "at",
            tutoringText: "Usamos 'at' para locais específicos ou pontos de encontro na cidade.",
          },
        ],
      },
      { nome: "Pós-teste", concluida: false },
    ],
    completo: false,
  },
];
