export const cursos = [
  {
    id: "7cf00315-225c-4217-82e7-7badd5681eee",
    nome: "to-be",
    titulo: "To Be",
    concluido: 0,
    atividades: [
      {
        nome: "Pré-teste",
        perguntas: [
          {
            titulo: "Escolha a resposta correta:",
            descricao: "I .......................... a teacher.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 1,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "You ...................... a great student.",
            opcoes: ["am", "is", "are", "do"],
            opcaoCorreta: 2,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "He ........................... a chef.",
            opcoes: ["am", "are", "do", "is"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "She ........................... a police officer.",
            opcoes: ["am", "are", "do", "is"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "It ...................... a good tool for my job.",
            opcoes: ["am", "are", "do", "is"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "We ............... engineers.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 2,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "They ..................... doctors.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 2,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "My sister and I ...................... lawyers.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 2,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "My cousin .......................... a firefighter.",
            opcoes: ["am", "are", "do", "is"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "The boss and the secretary .................................... in the meeting.",
            opcoes: ["am", "do", "is", "are"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "The client ........................ waiting outside.",
            opcoes: ["am", "are", "do", "is"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "I .......................... working as a journalist.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 1,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "She ........................... the new manager.",
            opcoes: ["am", "are", "do", "is"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "You and he ......................... marketing specialists.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 2,
          },
        ],
        concluida: false,
        dataConclusao: "",
      },
      {
        nome: "Conteúdo",
        videos: [
          {
            videoId: "verbotobe.mp4",
          },
        ],
        concluida: false,
      },
      {
        nome: "Quizz",
        concluida: false,
        perguntas: [
          {
            id: 1,
            sentence: "I ___ a student.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "am",
            tutoringText: "O pronome 'I' usa sempre a forma 'am' no presente do verbo 'to be'.",
          },
          {
            id: 2,
            sentence: "Barbara ___ not at home.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "is",
            tutoringText: "'Barbara' (singular, She) usa 'is not' ou 'isn't'.",
          },
          {
            id: 3,
            sentence: "___ you happy?",
            options: ["Is", "Are", "Am", "Be"],
            correctAnswer: "Are",
            tutoringText: "Na forma interrogativa, 'you' usa 'Are'.",
          },
          {
            id: 4,
            sentence: "Josh and Ricky ___ teachers.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "are",
            tutoringText: "'Josh and Ricky' (plural, They) usa 'are' no presente afirmativo.",
          },
          {
            id: 5,
            sentence: "We ___ not witches.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "are",
            tutoringText: "Na negativa, 'we' usa 'are not' ou 'aren't'.",
          },
          {
            id: 6,
            sentence: "___ Alan an accountant?",
            options: ["Is", "Are", "Am", "Be"],
            correctAnswer: "Is",
            tutoringText: "'Alan' (singular, He) usa 'Is' na forma interrogativa.",
          },
          {
            id: 7,
            sentence: "I ___ not a vampire.",
            options: ["is", "am", "are", "be"],
            correctAnswer: "am",
            tutoringText: "'I' na negativa usa 'am not'.",
          },
          {
            id: 8,
            sentence: "You ___ a witch.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "are",
            tutoringText: "'You' no presente afirmativo usa 'are'.",
          },
          {
            id: 9,
            sentence: "___ they vampires?",
            options: ["Is", "Are", "Am", "Be"],
            correctAnswer: "Are",
            tutoringText: "Na forma interrogativa, 'they' usa 'Are'.",
          },
          {
            id: 10,
            sentence: "Kevin ___ not a doctor.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "is",
            tutoringText: "'Kevin' (singular, He) usa 'is not' ou 'isn't' na negativa.",
          },
          {
            id: 11,
            sentence: "My friends ___ brothers and sisters.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "are",
            tutoringText: "'My parents' (plural, They) usa 'are' no presente afirmativo.",
          },
          {
            id: 12,
            sentence: "___ I human?",
            options: ["Is", "Are", "Am", "Be"],
            correctAnswer: "Am",
            tutoringText: "Na forma interrogativa, 'I' usa 'Am'.",
          },
          {
            id: 13,
            sentence: "Laura ___ a nurse.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "is",
            tutoringText: "'Laura' (singular, She) no afirmativo usa 'is'.",
          },
          {
            id: 14,
            sentence: "You ___ not my friend.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "are",
            tutoringText: "'You' na forma negativa usa 'are not' ou 'aren't'.",
          },
          {
            id: 15,
            sentence: "___ Paul a doctor or an engineer?",
            options: ["Is", "Are", "Am", "Be"],
            correctAnswer: "Is",
            tutoringText: "'Paul' (singular, He) usa 'Is' na forma interrogativa.",
          },
          {
            id: 16,
            sentence: "The paiting ___ a beautiful landscape.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "is",
            tutoringText: "'The meeting' (singular, It) usa a forma 'is' no presente.",
          },
          {
            id: 17,
            sentence: "We ___ in the office right now.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "are",
            tutoringText: "'We' usa 'are' para indicar a localização no presente.",
          },
          {
            id: 18,
            sentence: "Our colleagues ___ not ready for the exam.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "are",
            tutoringText: "'Our colleagues' (plural, They) usa 'are not' ou 'aren't' na negativa.",
          },
          {
            id: 19,
            sentence: "___ Martha a lawyer?",
            options: ["Is", "Are", "Am", "Be"],
            correctAnswer: "Is",
            tutoringText: "'Martha' (singular, She) usa 'Is' na forma interrogativa.",
          },
          {
            id: 20,
            sentence: "I ___ hungry.",
            options: ["is", "are", "am", "be"],
            correctAnswer: "am",
            tutoringText: "",
          },
        ],
        dataConclusao: "",
      },
      {
        nome: "Pós-teste",
        concluida: false,
        perguntas: [
          {
            titulo: "Escolha a resposta correta:",
            descricao: "My room ..........................clean.",
            opcoes: ["am", "is", "are", "will"],
            opcaoCorreta: 1,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "The cat ......................in the tree.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 0,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "David and Robert ...........................boys.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 2,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "My grandmother ...........................sick.",
            opcoes: ["am", "are", "do", "is"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "Anna ......................my sister",
            opcoes: ["am", "is", "are", "do"],
            opcaoCorreta: 1,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "The chair ...............short.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 0,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "The dog .....................under the table.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 0,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "I ......................under the table.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 1,
          },
          {
            titulo: "Qual das opções abaixo está NEGANDO a frase abaixo",
            descricao: "They are in my Office.",
            opcoes: [
              "They are in my Office not.",
              "They not are in my Office.",
              "They are not in my Office.",
              "They are in my not Office.",
            ],
            opcaoCorreta: 2,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "I ..........................from Spain.",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 1,
          },
          {
            titulo: "Qual das opções abaixo está PERGUNTANDO corretamente",
            descricao: "He is a good teacher.",
            opcoes: ["He is a good teacher?", "is he a good teacher?", "good teacher He is.", "good teacher a is he."],
            opcaoCorreta: 1,
          },
          {
            titulo: "Escolha a resposta correta:",
            dica: "Book está no plural",
            descricao: "The books .................................on the table",
            opcoes: ["is", "am", "are", "do"],
            opcaoCorreta: 2,
          },
          {
            titulo: "Qual das opções abaixo está PERGUNTANDO corretamente",
            descricao: "It is my pen.",
            opcoes: ["is it my pen?", "am it my pen?", "are it my pen?", "do it my pen?"],
            opcaoCorreta: 0,
          },
          {
            titulo: "Escolha a resposta correta:",
            descricao: "Tony and Jake ....................................a student.",
            opcoes: ["am", "do", "is", "are"],
            opcaoCorreta: 3,
          },
          {
            titulo: "Qual das opções abaixo está NEGANDO a frase abaixo",
            descricao: "They are students.",
            opcoes: ["They not are students.", "They are students not.", "students They are not.", "They are not students."],
            opcaoCorreta: 3,
          },
          {
            titulo: "Qual das opções abaixo está PERGUNTANDO corretamente",
            descricao: "We are brazillians.",
            opcoes: ["Are we brazillians?", "we are brazillians?", "do we be brazillians?", "be we brazillians?"],
            opcaoCorreta: 0,
          },
        ],
        dataConclusao: "2025-10-07T21:45:49.278Z",
      },
      {
        nome: "Memorização",
        concluida: false,
      },
    ],
    completo: false,
  },
  {
    id: "7cf00315-225c-4217-82e7-7badd5682eee",
    nome: "present-continuous",
    titulo: "Present Continuous",
    concluido: 5,
    atividades: [
      { nome: "Pré-teste", concluida: true, dataConclusao: new Date("2025-09-10T10:00:00") },
      { nome: "Conteúdo", concluida: true },
      { nome: "Quizz", concluida: true },
      { nome: "Pós-teste", concluida: false },
    ],
    completo: false,
  },
  {
    id: "7cf00315-225c-4217-82e7-7badd5683eee",
    nome: "simple-past",
    titulo: "Simple Past",
    concluido: 0,
    atividades: [
      { nome: "Pré-teste", concluida: true, dataConclusao: new Date("2025-09-10T10:00:00") },
      { nome: "Conteúdo", concluida: true },
      { nome: "Quizz", concluida: true },
      { nome: "Pós-teste", concluida: false },
    ],
    completo: false,
  },
];
