name: Deploy Static Website to S3

on:
  push:
    branches:
      - master  # Runs when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build App
        run: |
          npm i --legacy-peer-deps
          npm run build

      - name: Sync next files to S3
        run: |
          aws s3 sync ./dist/stock-marquetim/browser s3://spikai/ --delete --exclude "resource/*" --exclude "resource"
  deploy:
      if: contains(github.event.head_commit.message, 'lambda:')  # <-- só roda se tiver "lambda:" na mensagem
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '18'

        - name: Install dependencies
          run: |
          cd funcoes/cadastro 
          npm install

        - name: Zip Lambda function
          run: zip -r lambda-cadastro.zip ./funcoes/cadastro/index.js ./funcoes/cadastro/node_modules

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Deploy to AWS Lambda
          run: |
            aws lambda update-function-code \
              --function-name cadastro \
              --zip-file fileb://lambda-cadastro.zip
    
