name: Deploy Lambda and Website

on:
  push:
    branches:
      - master
    paths:
      - 'front/**'
      - 'function/user-module/**'
      - 'function/user-module-sprg/**'
  pull_request:
    branches:
      - master
    paths:
      - 'front/**'
      - 'function/user-module/**'
      - 'function/user-module-sprg/**'

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Check for front-end changes
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: front/**

      - name: Set Environment Variables
        id: set-env
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "BUCKET=spikai-dev" >> $GITHUB_OUTPUT
            echo "ENV=dev" >> $GITHUB_OUTPUT
          else
            echo "BUCKET=spikai" >> $GITHUB_OUTPUT
            echo "ENV=prod" >> $GITHUB_OUTPUT
          fi

      - name: Build and Sync to S3
        if: steps.changed-files.outputs.any_changed == 'true' || contains(github.event.head_commit.message, 'all:')
        working-directory: front
        run: |
          npm i --legacy-peer-deps
          npm run build
          aws s3 sync ./dist/stock-marquetim/browser s3://${{ steps.set-env.outputs.BUCKET }}/ --delete --exclude "resource/*" --exclude "resource"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

  deploy-lambda-usuario:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for lambda changes
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: function/user-module/**

      - name: Set Lambda Name
        id: set-name
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "FUNCTION_NAME=user-module-dev" >> $GITHUB_OUTPUT
          else
            echo "FUNCTION_NAME=user-module" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to AWS Lambda
        if: steps.changed-files.outputs.any_changed == 'true' || contains(github.event.head_commit.message, 'all:')
        working-directory: function/user-module
        run: |
          npm install 
          npm run build 
          npm prune --production
          zip -r lambda-user-module.zip dist node_modules package.json
          aws lambda update-function-code \
            --function-name ${{ steps.set-name.outputs.FUNCTION_NAME }} \
            --zip-file fileb://lambda-user-module.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}


  deploy-lambda-usr-spring:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Check for lambda changes
          id: changed-files
          uses: tj-actions/changed-files@v44
          with:
            files: function/user-module-sprg/**

        - name: Set Lambda Name
          id: set-name
          run: |
            if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              echo "FUNCTION_NAME=user-module-sprg-dev" >> $GITHUB_OUTPUT
            else
              echo "FUNCTION_NAME=user-module-sprg" >> $GITHUB_OUTPUT
            fi

        - name: Deploy to AWS Lambda (Java Spring Boot)
          if: steps.changed-files.outputs.any_changed == 'true' || contains(github.event.head_commit.message, 'all:')
          working-directory: function/user-module-sprg
          run: |
            mvn clean package -DskipTests

            aws lambda update-function-code \
              --function-name ${{ steps.set-name.outputs.FUNCTION_NAME }} \
              --zip-file fileb://target/usermodule-0.0.1-SNAPSHOT-aws.jar
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}